-- AlterTable
ALTER TABLE "neos" ADD COLUMN     "ratingCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "ratingSore" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "rejectCount" INTEGER NOT NULL DEFAULT 0;
